import React from 'react'
import { ScrollView, StyleSheet } from 'react-native';
import { View, Text, TouchableOpacity } from 'react-native'
import { Avatar } from 'react-native-paper';
import Appbar from '../../components/Appbar';

export default function AddModel({ navigation, route }) {
    const { carid } = route.params;

    const carmodels = [
        { id: 'audi', car: 'Audi', model: 'A3', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A3 Cabriolet', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A4', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A5', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A6', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A7', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A8', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'A8L', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Etron', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Q2', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Q3', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Q5', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Q7', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'Q8', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'R8', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'RS5', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'RS6 Avant', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'RS7', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'RS7 Sportsback', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'S5', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'S5 Sportsback', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'S6', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },
        { id: 'audi', car: 'Audi', model: 'TT', image: "https://rmechanic.herokuapp.com/assets/images/audi.jpg" },

        { id: 'bmw', car: 'Bmw', model: '1 Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '3 Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '3 series Gran Turismo', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '3581 I', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '5 Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '6 Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '6 Series Gran Turismo', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '7 Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: '8 Series Convertible', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'Gran Turismo', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'i3 S', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'M Series', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'M2', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'M3', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'M4', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'M5', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X1', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X3', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X4', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X5', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X5 M', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X6', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X6 M', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'X7', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },
        { id: 'bmw', car: 'Bmw', model: 'Z4', image: "https://rmechanic.herokuapp.com/assets/images/bmw.jpg" },

        { id: 'chevy', car: 'Chevrolet', model: 'Aveo', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Aveo UVA', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Beat', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Beat Activ', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Captiva', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'CN100', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Cruze', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Enjoy', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Essentia', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Forester', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Optra', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Optra Magnum', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Sail', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Sail Hatchback', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Spark', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Spin', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Tavera', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Tavera Neo', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },
        { id: 'chevy', car: 'Chevrolet', model: 'Trailblazer', image: "https://rmechanic.herokuapp.com/assets/images/chevy.jpg" },




        { id: 'fiat', car: 'Fiat', model: '1100', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: '500', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Abarth 595', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Adventure', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Ducato', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Grande Punto', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Linea', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Linea Classic', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Palio', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Palio D', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Palio NV', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Palio Stile', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Palip Stile Multijet', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Petra', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Premier Padmini', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Punto', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Punto Abarth', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Punto Evo', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Siena', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Uno', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },
        { id: 'fiat', car: 'Fiat', model: 'Urban Cross', image: "https://rmechanic.herokuapp.com/assets/images/fiat.jpg" },


        { id: 'ford', car: 'Ford', model: 'Classic', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Ecosoprt', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Endaevour', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Escort', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Falcon', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Fiesta', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Fiesta Classic', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Figo', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Figo Aspire', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Freestyle', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Ikon', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Mondeo', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'Mustang', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'New Endaevour', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },
        { id: 'ford', car: 'Ford', model: 'New Ikon', image: "https://rmechanic.herokuapp.com/assets/images/ford.jpg" },

        { id: 'honda', car: 'Honda', model: 'Accord', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Accord Hybrid', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Amaze', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'BR V', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Brio', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'City', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'City ZX', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Civic', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'CR V', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Jazz', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Mobilio', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'Step WGN', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },
        { id: 'honda', car: 'Honda', model: 'WR V', image: "https://rmechanic.herokuapp.com/assets/images/honda.jpg" },



        { id: 'hyundai', car: 'Hyundai', model: 'Verna', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Accent', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Aura', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Bayon', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Creta', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Elantra', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Elite i20', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'EON', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Getz', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Getz Prime', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Grand i10', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'i10', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'i20', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'i20 Activ', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },
        { id: 'hyundai', car: 'Hyundai', model: 'Kona Electric', image: "https://rmechanic.herokuapp.com/assets/images/hyundai.jpg" },


        { id: 'jeep', car: 'Jeep', model: 'Compass', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },
        { id: 'jeep', car: 'Jeep', model: 'Grand Cherokee', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },
        { id: 'jeep', car: 'Jeep', model: 'Grand Cherokee SRT', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },
        { id: 'jeep', car: 'Jeep', model: 'Wrangler', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },
        { id: 'jeep', car: 'Jeep', model: 'Wrangler Rubicon 392', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },
        { id: 'jeep', car: 'Jeep', model: 'Wrangler Unlimited', image: "https://rmechanic.herokuapp.com/assets/images/jeep.jpg" },




        { id: 'kia', car: 'Kia', model: 'Carnival', image: "https://rmechanic.herokuapp.com/assets/images/kia.jpg" },
        { id: 'kia', car: 'Kia', model: 'Seltos', image: "https://rmechanic.herokuapp.com/assets/images/kia.jpg" },
        { id: 'kia', car: 'Kia', model: 'Sonet', image: "https://rmechanic.herokuapp.com/assets/images/kia.jpg" },
        { id: 'kia', car: 'Kia', model: 'Telluride', image: "https://rmechanic.herokuapp.com/assets/images/kia.jpg" },




        { id: 'mahindra', car: 'Mahindra', model: 'Alturas G4', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Armada', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Bolero', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'e-Verito', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'e20 Plus', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Ingenio', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Jeep', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'KUV 100', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Logan', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Marazzo', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Nuvo Sport', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Quanto', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Scorpio', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Scorpio W', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Supro', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Thar', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'TUV 300', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'TUV 300 Plus', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Verito', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Verito Vibe', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Voyeger', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'W201', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'Willys', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'XUV', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'XUV 300', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'XUV 500', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },
        { id: 'mahindra', car: 'Mahindra', model: 'XYLO', image: "https://rmechanic.herokuapp.com/assets/images/mahindra.jpg" },


        { id: 'mercedes', car: 'Mercedes', model: '300', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'A Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'AMG GTS', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'AMG Series', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'B Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'C Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'C Class CLK', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'CL Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'CLA Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'CLK Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'CLS Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'E Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'E Class All terrain', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'EQC', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'G', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'G Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GL Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLA', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLA 45 AMG', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLA Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLB', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLC', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLE', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLE Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'GLS', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'M Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'MB Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'New C Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'R', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'R Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'S Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'S Class Cabriolet', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'SL Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'SLK Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'SLS AMG', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'V Class', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },
        { id: 'mercedes', car: 'Mercedes', model: 'Viano', image: "https://rmechanic.herokuapp.com/assets/images/mercedes.jpg" },


        { id: 'mg', car: 'MG', model: 'Gloster', image: "https://rmechanic.herokuapp.com/assets/images/mg.jpg" },
        { id: 'mg', car: 'MG', model: 'Hector', image: "https://rmechanic.herokuapp.com/assets/images/mg.jpg" },
        { id: 'mg', car: 'MG', model: 'Hector Plus', image: "https://rmechanic.herokuapp.com/assets/images/mg.jpg" },
        { id: 'mg', car: 'MG', model: 'ZS', image: "https://rmechanic.herokuapp.com/assets/images/mg.jpg" },

        { id: 'nissan', car: 'Nissan', model: '350Z', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: '370Z', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Cima', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Evalia', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Gloria', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'GTR', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Jonga', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Kicks', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Magnite', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Micra', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Micra Activ', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Sunny', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Teana', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Terrano', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'Tiida', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },
        { id: 'nissan', car: 'Nissan', model: 'X Trail', image: "https://rmechanic.herokuapp.com/assets/images/nissan.jpg" },


        { id: 'renault', car: 'Renault', model: 'Captur', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Duster', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Fluence', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Kiger', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Koleos', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Kwid', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Lodgy', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Pulse', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Scala', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },
        { id: 'renault', car: 'Renault', model: 'Triber', image: "https://rmechanic.herokuapp.com/assets/images/renault.jpg" },

        { id: 'skoda', car: 'Skoda', model: 'Fabia', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Kamiq', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Karoq', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Kodiaq', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Laura', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Laura VRS', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'New Octavia', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'OCtavia Ambiente', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Octavia Classic', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Octavia Combi', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Octavia Rider', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Octavia RS', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Rapid', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Superb', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },
        { id: 'skoda', car: 'Skoda', model: 'Yeti', image: "https://rmechanic.herokuapp.com/assets/images/skoda.jpg" },


        { id: 'suzuki', car: 'Suzuki', model: '1000', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: '800', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'A Star', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Alto', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Alto 800', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Alto K10', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Baleno', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Celerio', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Celerio X', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Ciaz', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Eeco', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Esteem', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Ertiga', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Estilo', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Grand Vitara', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Gypsy', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Ignis', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Jimny', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Kizashi', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Omni', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Ritz', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'S Cross', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'S Presso', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Swift', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Swift Dzire', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'SX4', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Versa', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Vitara Brezza', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Wagon R', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'Wagon R Stingray', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },
        { id: 'suzuki', car: 'Suzuki', model: 'XL6', image: "https://rmechanic.herokuapp.com/assets/images/suzuki.jpg" },


        { id: 'toyota', car: 'Toyota', model: 'Alphard', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Camry', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Commuter', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Corolla', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Corolla Altis', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Corona', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Crown', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'CRX', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Cynos', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Estima Emina', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Etios', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Etios Cross', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Fortuner', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Glanza', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'HI Ace Van', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Innova', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Innova Crysta', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Land Cruiser', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Land Cruiser Prado', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Majesta', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'MR2', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'MR5', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Prado', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Prius', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Qualis', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Sera', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Tercel', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Trueno', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Urban Cruiser', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Vellfire', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },
        { id: 'toyota', car: 'Toyota', model: 'Yaris', image: "https://rmechanic.herokuapp.com/assets/images/toyota.jpg" },

        { id: 'tata', car: 'Tata', model: 'Altroz', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Aria', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Bolt', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Estate', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Gravitas', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Harrier', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Hexa', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Hornbill HBX', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indica', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indica Ev2', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indica V2', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indica Vista', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indica Xeta BS IV', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indicab', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indicruz', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo CS', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo ECS', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo Marina', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo V', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo Vista', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Indigo XL', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Kite Sedan', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Manza', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Manza Elan', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Movus', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'NANO', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'New', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Nexon', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Nexon Ev', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Pelican', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Safari Storme', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Sierra', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Sumo', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Sumo Grande', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Sumo Spacio', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Sumo Victa', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Tiago', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Tiger', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Tl', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Venture', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Vista', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Winger', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Winger Platinum', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'Xenon XT', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },
        { id: 'tata', car: 'Tata', model: 'ZEST', image: "https://rmechanic.herokuapp.com/assets/images/tata.jpg" },


        { id: 'volkswagen', car: 'Volkswagen', model: '1600', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Ameo', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Beetle', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Caravelle', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Cross Polo', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Jetta', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Passat', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Phaeton', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Polo', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Polo GT', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Polo GTi', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'T-Roc', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Taigun', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
        { id: 'volkswagen', car: 'Volkswagen', model: 'Taigun', image: "https://rmechanic.herokuapp.com/assets/images/volkswagen.jpg" },
    ]

    return (
        <View style={{ flex: 1 }}>
            <Appbar title="SELECT MODEL" navigation={navigation} />
            <ScrollView scrollEventThrottle={16} style={{ flex: 1 }}>
                <Text style={{ fontFamily: "ManropeBold", fontSize: 18, padding: 10 }}>Select brand</Text>
                {
                    carmodels.map((item, index) => {
                        if (item.id == carid)
                            return (
                                <TouchableOpacity style={styles.card} key={index}>
                                    <Avatar.Image size={38} source={{ uri: item.image }} />
                                    <Text style={styles.label}>{item.model}</Text>
                                </TouchableOpacity>
                            );
                    })
                }
            </ScrollView>
        </View>
    )
}
const styles = StyleSheet.create({
    card: {
        backgroundColor: "#fff", paddingHorizontal: 10, paddingVertical: 15, marginBottom: 2, flexDirection: 'row', alignItems: 'center'
    },
    label: {
        fontFamily: 'ManropeBold', paddingHorizontal: 20,
    }
})
